# Final Thoughts {#FinalThoughts}

If you made it this far, a few themes should be apparent. The first is the important role of simulation in planning and conducting field research. Even writing the code to simulate a field study forces one to think about the design and parameters such as sample size that are under the investigator's control. Once the combined code for simulation and analysis is working, runs under different settings can show what is required to obtain useful results, at least for the simulated (ideal) case. The simulations and models used in this book can also be extended to include additional sources of error, such as ageing error or non-reporting\index{tag-reporting rate} or shedding of tags\index{tag loss}. This planning approach will also require some thought about what *is* a useful result, for example, a tolerable credible interval\index{credible interval} width or relative error ($\frac{\hat{\delta}-\delta}{\delta}$). Upfront simulation and planning improves the odds of a successful field study, or perhaps prevents a waste of time and money conducting a study that would not address management needs.

Another theme has been the value of JAGS in constructing and fitting fisheries models. In my experience, BUGS-family code is a valuable teaching tool, helping students visualize the models and how parameter estimates are obtained. Writing and running JAGS code is vastly superior to a black-box analysis from a learning perspective. From a research perspective, JAGS code can be tailored to the specific characteristics of a field study. Examples in this book hopefully have illustrated how auxiliary studies can be folded into a Bayesian analysis to improve parameter estimates. JAGS software is still popular and being actively developed, but there are now a number of options for Bayesian analysis [@strumbelj.etal_2024].  A new book by @kery.kellner_2024 on Bayesian model fitting using JAGS, Nimble, and Stan should be a good resource for exploring the strengths and weaknesses of those software packages. In any case, experience with JAGS should provide a strong foundation for future fisheries modeling, even if Bayesian analyses transition to next-generation software.

A third theme is the importance of learning by doing. Ideally, this includes not only writing code for simulation and analysis, but also carrying out the field work that builds experience and ecological intuition. Within the scope of this book, learning by doing means running and modifying code in order to understand fully how each analysis works. JAGS and especially R code can sometimes be cryptic, so I have encouraged running sections of code or even parts of a line of code in order to gain understanding. One of the best things about recent books on Bayesian analysis is the routine inclusion of code. Seeing, running and modifying the code is a great help in understanding how these models work.

This is intended to be an introductory text, so some important topics were not covered or only mentioned in passing. The binomial-mixture model (Section \@ref(NMix)) is a simple example of a hierarchical model\index{hierarchical model}, but the approach is much broader. Hierarchical modeling can be used to separate the observation process from the underlying ecological process (latent state) that is of primary interest [@royle.dorazio_2008]. @kéry.schaub_2012 illustrate this approach in a hierarchical population model for ibex (*Capra ibex*). Annual counts include both process error\index{process error} and observation error\index{observation error}, so a model that separates the two error sources provides more biologically relevant estimates of population parameters [@kéry.schaub_2012]. Recent publications using Bayesian hierarchical models have often been terrestrial studies [e.g., @johnson.etal_2010], but the concepts and analytical methods are entirely transferable to fisheries systems.

I have also not included some traditional fisheries models, such as the biomass dynamic or surplus production models that have been widely used for fish stock assessment [@hilborn.walters_1992]. These models have been popular because they are simple, require limited data, and provide an estimate of maximum sustainable yield\index{maximum sustainable yield}. Early versions often assumed equilibrium conditions that were rarely met [@hilborn.walters_1992]. Recent versions using non-equilibrium models [@meyer.millar_1999; @winker.etal_2018] illustrate the potential of a Bayesian analysis, including a state-space formulation\index{state-space model} for sorting out observation\index{observation error} and process\index{process error} error and use of informative priors\index{informative prior distribution}.

Another general fisheries topic not covered is yield or harvest modeling. We have focused on estimating population parameters, so the logical next step would be to use those parameter estimates to explore management options. For example, a yield model might be used to explore the potential benefits of regulation. The yield model would use information about fishing and natural mortality (Chapter \@ref(Mortality)), growth (Chapter \@ref(Growth)), and possibly recruitment\index{recruitment} (Chapter \@ref(Recruit)). The yield model could be constructed within an IPM\index{integrated population model (IPM)} (Chapter \@ref(PopModels)), so that the uncertainty associated with the various population parameters would not be lost. For a commercial fishery, the yield model would typically be in terms of weight, corresponding to how income is derived. The model could be used to examine the potential gains and losses from management options such as a quota or seasonal closure. For a recreational fishery, a yield model might focus on numbers (catch rate) rather than weight, or on the proportion of fish within "memorable" and "trophy" size ranges. Management for a recreational fishery is more likely to use creel and size regulations than quotas and could, for example, compare the benefits of various minimum and slot size limits. A recent article by @doll.etal_2021 perfectly illustrates these concepts using a Bayesian IPM\index{integrated population model (IPM)} fitted with JAGS.

@kéry_2010 closed his book with a prediction that, for many readers, WinBUGS will have "changed forever the way in which you think about, and conduct, statistical modeling." WinBUGS certainly started that process for me, followed by other BUGS-family variants including JAGS. It will be interesting to see the future contributions of Bayesian software packages to fisheries science and management.






